apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: springboot-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: springboot-deployment
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 75
