apiVersion: v1
kind: Service
metadata:
  name: rspringboot-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-app
  ports:
    - name: springboot-app
      protocol: TCP
      port: 9000
      targetPort: 9000
